# Simulation Exercises

## How likely is it that you roll doubles when rolling two dice?

In [1]:
import numpy as np
import pandas as pd

In [2]:
ntrials = ncols = 2
nsims = nrows = 100_000

rolls = pd.DataFrame(np.random.choice([1, 2, 3, 4, 5, 6], size=(nsims, ntrials)))
rolls

0  1
0      3  5
1      6  2
2      3  3
3      1  5
4      1  1
...   .. ..
99995  6  2
99996  1  4
99997  1  4
99998  2  2
99999  3  6

[100000 rows x 2 columns]

In [3]:
doubles = rolls[0] == rolls[1]
doubles

0        False
1        False
2         True
3        False
4         True
         ...  
99995    False
99996    False
99997    False
99998     True
99999    False
Length: 100000, dtype: bool

In [4]:
P_of_doubles = doubles.mean()
P_of_doubles

0.16789

## If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [5]:
ntrials = 8
nsims = 100_000

# 1 heads, 0 tails
flips = np.random.choice([0, 1], size=(nsims, ntrials))
flips

array([[1, 1, 1, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 1],
       [0, 1, 0, ..., 1, 1, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 1],
       [0, 1, 0, ..., 1, 0, 1],
       [0, 1, 1, ..., 0, 1, 1]])

In [6]:
exactly_3_heads = (flips == 1).sum(axis=1) == 3

In [7]:
exactly_3_heads.mean()

0.21759

In [8]:
more_than_3_heads = (flips == 1).sum(axis=1) > 3
more_than_3_heads

array([ True, False,  True, ..., False, False,  True])

In [9]:
more_than_3_heads.mean()

0.63819

## There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [10]:
ntrials = 1
nsims = 100_000

billboards = np.random.choice(['Web Dev', 'Data Science'], p=[3/4, 1/4], size=(nsims, ntrials))
billboards

array([['Web Dev'],
       ['Web Dev'],
       ['Web Dev'],
       ...,
       ['Web Dev'],
       ['Web Dev'],
       ['Web Dev']], dtype='<U12')

In [11]:
(billboards == 'Data Science').mean()

0.24882

## Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [12]:
ntrials = ncols = 5
nsims = nrows = 100_000

poptarts = np.random.normal(3, 1.5, size=(nrows, ncols)).round()
poptarts

array([[4., 1., 4., 3., 3.],
       [4., 2., 1., 4., 4.],
       [3., 2., 5., 4., 1.],
       ...,
       [3., 5., 4., 3., 2.],
       [4., 3., 4., 1., 3.],
       [3., 5., 5., 3., 3.]])

In [13]:
no_neg_poptarts = np.where(poptarts < 0, 0, poptarts)
no_neg_poptarts

array([[4., 1., 4., 3., 3.],
       [4., 2., 1., 4., 4.],
       [3., 2., 5., 4., 1.],
       ...,
       [3., 5., 4., 3., 2.],
       [4., 3., 4., 1., 3.],
       [3., 5., 5., 3., 3.]])

In [14]:
has_left_overs = no_neg_poptarts.sum(axis=1) < 17
has_left_overs

array([ True,  True,  True, ..., False,  True, False])

In [15]:
has_left_overs.mean()

0.66867

## Compare Heights

* Men have an average height of 178 cm and standard deviation of 8cm.
* Women have a mean of 170, sd = 6cm.
* If a man and woman are chosen at random, P(woman taller than man)?

In [16]:
nsims = 100_000

men = np.random.normal(178, 8, size=nsims)
men

array([172.44353843, 172.63888954, 181.22563437, ..., 177.25446465,
       175.07950699, 176.02429863])

In [17]:
women = np.random.normal(170, 6, size=nsims)
women

array([164.55537908, 166.98212721, 170.11514042, ..., 175.63945316,
       168.39697632, 165.27048344])

In [18]:
(men < women).mean()

0.21164

## When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [19]:
def prob_no_anaconda_corruption(students, number_of_sims_to_run):
    ntrials = ncols = students
    nsims = nrows = number_of_sims_to_run

    installs = np.random.choice([0, 1], p=[1/250, 249/250], size=(nrows, ncols))
    
    no_corruptions = installs.sum(axis=1) == students
    
    return no_corruptions.mean()

In [20]:
prob_no_anaconda_corruption(50, 100_000)

0.81641

In [21]:
prob_no_anaconda_corruption(100, 100_000)

0.67015

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [22]:
def prob_anaconda_corruption(students, number_of_sims_to_run):
    ntrials = ncols = students
    nsims = nrows = number_of_sims_to_run

    installs = np.random.choice([0, 1], p=[1/250, 249/250], size=(nrows, ncols))
    
    has_corruptions = installs.sum(axis=1) < students
    
    return has_corruptions.mean()

In [23]:
prob_anaconda_corruption(150, 100_000)

0.44956

### How likely is it that 450 students all download anaconda without an issue?

In [24]:
prob_no_anaconda_corruption(450, 100_000)

0.16518

## There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [25]:
ntrials = 3
nsims = 100_000

# 0 is no food trucks, 1 is at least 1 food truck
food_trucks = np.random.choice([0, 1], p=[.3, .7], size=(nsims, ntrials))
food_trucks

array([[1, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       ...,
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
no_food_trucks = food_trucks.sum(axis=1) == 0
no_food_trucks

array([False, False, False, ..., False, False, False])

In [27]:
no_food_trucks.mean()

0.02713

### How likely is it that a food truck will show up sometime this week?

In [28]:
ntrials = 7
nsims = 100_000

food_trucks = np.random.choice([0, 1], p=[.3, .7], size =(nsims, ntrials))
food_trucks

array([[1, 1, 1, ..., 0, 0, 1],
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 1, 1]])

In [29]:
at_least_one_food_truck = food_trucks.sum(axis=1) > 0
at_least_one_food_truck

array([ True,  True,  True, ...,  True,  True,  True])

In [30]:
at_least_one_food_truck.mean()

0.99978

## If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [31]:
ntrials = 23
nsims = 100000

birthdays = pd.DataFrame(np.random.uniform(1, 366, size=(nsims, ntrials)).round())
birthdays

0      1      2      3      4      5      6      7      8      9   \
0        4.0  355.0   22.0  251.0   47.0  117.0   25.0  312.0  105.0  308.0   
1      119.0   17.0  355.0   39.0  318.0   33.0  330.0  133.0   75.0  161.0   
2      197.0  249.0  324.0  281.0  127.0  189.0  115.0  188.0   40.0  261.0   
3      174.0   61.0  138.0   96.0  133.0  304.0   14.0  290.0  281.0  195.0   
4      203.0  354.0  262.0  125.0  358.0  259.0  213.0  339.0  133.0    8.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
99995  326.0  300.0  140.0   32.0   53.0   51.0   93.0  123.0  189.0   75.0   
99996  221.0  155.0  185.0   55.0  292.0  197.0   52.0  263.0  208.0  151.0   
99997   78.0   21.0  331.0  151.0  311.0   20.0  139.0  294.0  108.0  302.0   
99998  206.0  175.0  234.0  101.0  209.0  131.0  301.0  261.0   56.0  156.0   
99999  250.0  245.0  357.0  228.0  107.0  149.0    5.0  254.0  172.0   33.0   

       ...     13     14     15     16     17     18     19     20     21  \
0      ...  284.0  198.0  166.0  114.0  144.0  174.0  254.0  101.0  190.0   
1      ...    6.0   66.0   96.0  331.0  228.0  106.0  163.0   22.0   40.0   
2      ...  311.0  222.0  107.0   53.0   12.0  108.0  189.0   24.0  262.0   
3      ...   29.0  116.0   55.0  255.0   29.0  232.0  234.0   57.0   29.0   
4      ...  205.0  218.0  136.0  321.0  132.0   91.0  280.0   54.0  125.0   
...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
99995  ...  210.0   45.0  134.0  218.0  183.0   33.0  109.0  312.0  278.0   
99996  ...   74.0  351.0   14.0  151.0   92.0  176.0  275.0  171.0  242.0   
99997  ...  111.0   91.0  143.0   11.0  146.0   90.0  153.0  334.0   23.0   
99998  ...  124.0  127.0   48.0  268.0   28.0  339.0  252.0  158.0   31.0   
99999  ...   62.0  256.0  322.0  160.0  173.0   90.0  304.0   21.0  360.0   

          22  
0      135.0  
1       51.0  
2      354.0  
3      139.0  
4      283.0  
...      ...  
99995  264.0  
99996  219.0  
99997  311.0  
99998  361.0  
99999  189.0  

[100000 rows x 23 columns]

In [32]:
def birthday_match(one_party):
    return one_party.duplicated().any()

In [33]:
matching_birthdays = birthdays.apply(birthday_match, axis=1)
matching_birthdays

0         True
1        False
2         True
3         True
4         True
         ...  
99995    False
99996     True
99997     True
99998    False
99999    False
Length: 100000, dtype: bool

In [34]:
matching_birthdays.mean()

0.50925

I'm going to make a function that excutes the above so that I can give each answer simply

In [35]:
def prob_of_mathching_birthdays(n_people, n_parties):
    ntrials = n_people
    nsims = n_parties

    birthdays = pd.DataFrame(np.random.uniform(1, 366, size=(nsims, ntrials)).round())
    print(f'Generated {n_parties} parties of {n_people} people')
    print('Checking for matches...')
    
    matching_birthdays = birthdays.apply(birthday_match, axis=1)
    print('Matches determined, calculating probability...')
    
    return matching_birthdays.mean()

In [36]:
prob_of_mathching_birthdays(23, 100000)

Generated 100000 parties of 23 people
Checking for matches...
Matches determined, calculating probability...


0.50713

In [37]:
prob_of_mathching_birthdays(20, 100000)

Generated 100000 parties of 20 people
Checking for matches...
Matches determined, calculating probability...


0.40975

In [38]:
prob_of_mathching_birthdays(40, 100000)

Generated 100000 parties of 40 people
Checking for matches...
Matches determined, calculating probability...


0.89134