# Simulation Exercises

## How likely is it that you roll doubles when rolling two dice?

In [1]:
import numpy as np
import pandas as pd

In [2]:
ntrials = ncols = 2
nsims = nrows = 10000

rolls = pd.DataFrame(np.random.choice([1, 2, 3, 4, 5, 6], size=(nsims, ntrials)))
rolls

0  1
0     6  4
1     1  5
2     1  6
3     4  5
4     3  4
...  .. ..
9995  3  5
9996  5  2
9997  6  6
9998  5  4
9999  3  6

[10000 rows x 2 columns]

In [3]:
doubles = rolls[0] == rolls[1]
doubles

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997     True
9998    False
9999    False
Length: 10000, dtype: bool

In [4]:
P_of_doubles = doubles.mean()
P_of_doubles

0.1626

## If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [5]:
ntrials = 8
nsims = 10000

# 1 heads, 0 tails
flips = np.random.choice([0, 1], size=(nsims, ntrials))
flips

array([[1, 1, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 1]])

In [6]:
exactly_3_heads = (flips == 1).sum(axis=1) == 3

In [7]:
exactly_3_heads.mean()

0.2172

In [8]:
more_than_3_heads = (flips == 1).sum(axis=1) > 3
more_than_3_heads

array([False, False, False, ..., False, False,  True])

In [9]:
more_than_3_heads.mean()

0.6377

## There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [10]:
ntrials = 1
nsims = 10000

billboards = np.random.choice(['Web Dev', 'Data Science'], p=[3/4, 1/4], size=(nsims, ntrials))
billboards

array([['Web Dev'],
       ['Data Science'],
       ['Web Dev'],
       ...,
       ['Web Dev'],
       ['Web Dev'],
       ['Web Dev']], dtype='<U12')

In [11]:
(billboards == 'Data Science').mean()

0.246

## Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [12]:
ntrials = ncols = 5
nsims = nrows = 1000000

poptarts = np.random.normal(3, 1.5, size=(nrows, ncols)).round()
poptarts

array([[3., 4., 3., 2., 3.],
       [2., 5., 2., 1., 3.],
       [0., 3., 5., 3., 2.],
       ...,
       [1., 3., 0., 3., 2.],
       [1., 5., 3., 4., 3.],
       [2., 4., 4., 3., 2.]])

In [13]:
no_neg_poptarts = np.where(poptarts < 0, 0, poptarts)
no_neg_poptarts

array([[3., 4., 3., 2., 3.],
       [2., 5., 2., 1., 3.],
       [0., 3., 5., 3., 2.],
       ...,
       [1., 3., 0., 3., 2.],
       [1., 5., 3., 4., 3.],
       [2., 4., 4., 3., 2.]])

In [14]:
has_left_overs = no_neg_poptarts.sum(axis=1) < 17
has_left_overs

array([ True,  True,  True, ...,  True,  True,  True])

In [15]:
has_left_overs.mean()

0.669472